/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ShipmentDetailsSnapshot {
  'trackingNumber' : string,
  'destination' : string,
  'origin' : string,
  'recipient' : string,
  'sender' : string,
  'events' : Array<ShipmentEventSnapshot>,
  'currentStatus' : string,
}
export interface ShipmentEventSnapshot {
  'status' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'addShipment' : ActorMethod<
    [string, string, string, string, string, string],
    boolean
  >,
  'addShipmentEvent' : ActorMethod<[string, bigint, string, string], boolean>,
  'getAllShipments' : ActorMethod<[], Array<[string, ShipmentDetailsSnapshot]>>,
  'getShipmentDetails' : ActorMethod<[string], [] | [ShipmentDetailsSnapshot]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];